apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application }}
  namespace: {{ .Values.namespace }}
stringData:
  POSTGRES_USER: {{ .Values.db_admin_user }}
  POSTGRES_PASSWORD: {{ .Values.db_admin_password }}
  POSTGRES_DB: {{ .Values.db_database }}
  POSTGRES_INITDB_ARGS: "--data-checksums"
  PGDATA: "/var/lib/postgresql/data/pgdata"
